# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EmailAPI/email.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='EmailAPI/email.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\020GrpcServiceEmail',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x45mailAPI/email.proto\"T\n\x0c\x45mailRequest\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"\x1e\n\rWasSuccessful\x12\r\n\x05value\x18\x01 \x01(\x08\x32\x37\n\x07\x45mailer\x12,\n\tSendEmail\x12\r.EmailRequest\x1a\x0e.WasSuccessful\"\x00\x42\x13\xaa\x02\x10GrpcServiceEmailb\x06proto3'
)




_EMAILREQUEST = _descriptor.Descriptor(
  name='EmailRequest',
  full_name='EmailRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='password', full_name='EmailRequest.password', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receiver', full_name='EmailRequest.receiver', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subject', full_name='EmailRequest.subject', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='EmailRequest.content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=108,
)


_WASSUCCESSFUL = _descriptor.Descriptor(
  name='WasSuccessful',
  full_name='WasSuccessful',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='WasSuccessful.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['EmailRequest'] = _EMAILREQUEST
DESCRIPTOR.message_types_by_name['WasSuccessful'] = _WASSUCCESSFUL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmailRequest = _reflection.GeneratedProtocolMessageType('EmailRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMAILREQUEST,
  '__module__' : 'EmailAPI.email_pb2'
  # @@protoc_insertion_point(class_scope:EmailRequest)
  })
_sym_db.RegisterMessage(EmailRequest)

WasSuccessful = _reflection.GeneratedProtocolMessageType('WasSuccessful', (_message.Message,), {
  'DESCRIPTOR' : _WASSUCCESSFUL,
  '__module__' : 'EmailAPI.email_pb2'
  # @@protoc_insertion_point(class_scope:WasSuccessful)
  })
_sym_db.RegisterMessage(WasSuccessful)


DESCRIPTOR._options = None

_EMAILER = _descriptor.ServiceDescriptor(
  name='Emailer',
  full_name='Emailer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=142,
  serialized_end=197,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendEmail',
    full_name='Emailer.SendEmail',
    index=0,
    containing_service=None,
    input_type=_EMAILREQUEST,
    output_type=_WASSUCCESSFUL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMAILER)

DESCRIPTOR.services_by_name['Emailer'] = _EMAILER

# @@protoc_insertion_point(module_scope)
