# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import email_pb2 as EmailAPI_dot_email__pb2


class EmailerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendEmail = channel.unary_unary(
                '/Emailer/SendEmail',
                request_serializer=EmailAPI_dot_email__pb2.EmailRequest.SerializeToString,
                response_deserializer=EmailAPI_dot_email__pb2.WasSuccessful.FromString,
                )


class EmailerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmailerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEmail,
                    request_deserializer=EmailAPI_dot_email__pb2.EmailRequest.FromString,
                    response_serializer=EmailAPI_dot_email__pb2.WasSuccessful.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Emailer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Emailer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Emailer/SendEmail',
            EmailAPI_dot_email__pb2.EmailRequest.SerializeToString,
            EmailAPI_dot_email__pb2.WasSuccessful.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
